// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using NUnit.Framework;

namespace Tests
{
		[TestFixture]
		public class CharacterTests
		{
				[Test]
				public void BasicConstructor()
				{
					Character c = new Character(70);
					
					Assert.AreEqual(70, c.CurrentHP);
				}
				
				[Test]
				public void TakesDamageCorrectly()
				{
					Character c = new Character(70);
					
					c.TakeDamage(50);
					
					Assert.AreEqual(20, c.CurrentHP);
				}
				
				[Test]
				public void HealsCorrectly()
				{
					Character c = new Character(70);
					
					c.TakeDamage(50);
					c.TakeDamage(-10);
					
					Assert.AreEqual(30, c.CurrentHP);
				}
				
				[Test]
				public void CannotExceedMaxHP()
				{
					Character c = new Character(70);
					
					c.TakeDamage(-10);
					
					Assert.AreEqual(70, c.CurrentHP);
				}
				
				[Test]
				public void ZeroHP()
				{
					Character c = new Character(70);
					
					c.TakeDamage(80);
					
					Assert.AreEqual (0, c.CurrentHP);
				}
				
				[Test]
				public void IsDead()
				{
					Character c = new Character(70);
					
					c.TakeDamage(70);
					
					Assert.IsTrue(c.isDead());
				}
		}
}

